version: '2.1'
services:
  express_api:
    build: .
    image: express_api
    user: node
    working_dir: /home/node/app
    volumes:
      - ./:/home/node/app
    ports:
      - 7770:7770
    environment:
      - POSTGRES_HOST=database
    depends_on:
      - database
    env_file:
      - .env
  database:
    image: postgres:9.6
    volumes:
      - database:/var/lib/postgresql/data
    ports:
      - 7772:5432
    env_file:
      - .env
volumes:
  database:
